#!/bin/bash -l
# set -e

GITDIR="/root/gcp-gke"

# Set workdir
set-workdir ${GITDIR}/us-central


# Store our project ID as a Terraform env var
grep $INSTRUQT_GCP_PROJECT_GCP_PROJECT_PROJECT_ID /root/.bashrc || echo "export TF_VAR_gcp_project=\"$INSTRUQT_GCP_PROJECT_GCP_PROJECT_PROJECT_ID\"" >> /root/.bashrc
grep "GOOGLE_PROJECT=" /root/.bashrc || echo "export GOOGLE_PROJECT=\"$INSTRUQT_GCP_PROJECT_GCP_PROJECT_PROJECT_ID\"" >> /root/.bashrc

# Add GCP Credentials to our profile and env
export GOOGLE_CREDENTIALS=$(echo $INSTRUQT_GCP_PROJECT_GCP_PROJECT_SERVICE_ACCOUNT_KEY | base64 -d | jq 'tostring')
grep "GOOGLE_CREDENTIALS=" /root/.bashrc || echo "export GOOGLE_CREDENTIALS=$GOOGLE_CREDENTIALS" >> /root/.bashrc

# save primary cluster root key to a file
echo $(jq -r '.root_token' < ${GITDIR}/us-west/tmp/cluster-keys.json) > ${GITDIR}/us-west/tmp/root.token.primary.json
exit 0

