version: "2"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/terraform-workstation-3-5-0
  shell: /bin/bash -l
  machine_type: n1-standard-1
gcp_projects:
- name: gcp-project
  services:
  - cloudresourcemanager.googleapis.com
  - compute.googleapis.com
  - container.googleapis.com
  - cloudkms.googleapis.com
