#!/bin/bash
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

kubectl --context=usc exec -ti vault-usc-0 -- vault read sys/replication/dr/status

exit 0
