#!/bin/bash -l
sleep 30

set-workdir /root/aws/consul

#inital vault
vault_lb=$(terraform output -state /root/aws/consul/terraform.tfstate vault_url)
export VAULT_ADDR=http://${vault_lb}
master_token=$(terraform output -state /root/aws/consul/terraform.tfstate master_token)
agent_server_token=$(terraform output -state /root/aws/consul/terraform.tfstate agent_server_token)
gossip_key=$(terraform output -state /root/aws/consul/terraform.tfstate gossip_key)
snapshot_token=$(terraform output -state /root/aws/consul/terraform.tfstate snapshot_token)

vault login root
vault kv put secret/consul master_token=${master_token} agent_server_token=${agent_server_token} snapshot_token=${snapshot_token} gossip_key=${gossip_key}

vault auth enable userpass
vault write auth/userpass/users/operations password=Password1 policies=ops token_ttl=8h
vault write auth/userpass/users/backend password=Password1 policies=backend token_ttl=30m
vault write auth/userpass/users/frontend password=Password1 policies=frontend token_ttl=30m
vault secrets enable consul

echo 'path "secret/*" {
  capabilities = ["list"]
}
path "secret/data/consul" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "consul/*"
{
  capabilities = ["create", "read", "update", "delete"]
}' | vault policy write ops -

echo 'path "consul/creds/backend-developer"
{
  capabilities = ["read"]
}' | vault policy write backend -

echo 'path "consul/creds/frontend-developer"
{
  capabilities = ["read"]
}' | vault policy write frontend -

unset VAULT_TOKEN

vault login -method=userpass username=operations password=Password1

export CONSUL_HTTP_TOKEN=$(vault kv get -field=master_token secret/consul)
vault_consul_mgmt_token=$(consul acl token create -policy-name=global-management -description "vault mgmt" | grep SecretID | cut -d ":" -f2 | xargs)
vault write consul/config/access address="${CONSUL_HTTP_ADDR}" token=${vault_consul_mgmt_token}


consul acl policy create -name "ops" -description "admin policy for ops" -rules 'acl = "write" operator = "write" namespace_prefix "" {acl = "write"}'
vault write consul/roles/ops policies=ops ttl=1h

# Get dynamically generated "ops" consul token from Vault
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/ops)

# Setup Anonymous Policy
echo '
    node_prefix "" {
      policy = "read"
    }
    session_prefix "" {
      policy = "read"
    }
    agent_prefix "" {
      policy = "read"
    }
    query_prefix "" {
      policy = "read"
    }
    operator = "read"
    namespace_prefix "" {
      acl = "read"
      intention = "read"
      service_prefix "" {
        policy = "read"
      }
      node_prefix "" {
        policy = "read"
      }
    }' |  consul acl policy create -name anonymous -rules -
    consul acl token update -id anonymous -policy-name anonymous

mkdir -p /root/aws/policies
cat << EOF > /root/aws/policies/svc-policy.hcl
service_prefix "" {
  policy = "write"
}
EOF


# Set Consul Env
echo "Setup Consul profile"
cat <<PROFILE | sudo tee /etc/profile.d/consul.sh
export CONSUL_HTTP_ADDR=$(terraform output -state /root/aws/consul/terraform.tfstate dns_name)
export CONSUL_HTTP_TOKEN=$(terraform output -state /root/aws/consul/terraform.tfstate master_token)
export VAULT_ADDR=http://${vault_lb}
PROFILE

sed -i "s/\/root\/aws.*/\/root\/aws/" /etc/systemd/system/code-server.service
systemctl daemon-reload
systemctl restart code-server

exit 0
