#!/bin/bash

vault login -method=userpass username=operations password=Password1

export CONSUL_HTTP_TOKEN=$(vault kv get -field=master_token secret/consul)
vault_consul_mgmt_token=$(consul acl token create -policy-name=global-management -description "vault mgmt" | grep SecretID | cut -d ":" -f2 | xargs)
vault write consul/config/access address="${CONSUL_HTTP_ADDR}" token=${vault_consul_mgmt_token}


consul acl policy create -name "ops" -description "admin policy for ops" -rules 'acl = "write" operator = "write" namespace_prefix "" {acl = "write"}'
vault write consul/roles/ops policies=ops ttl=1h
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/ops)

# Setup Anonymous Policy
echo '
    node_prefix "" {
      policy = "read"
    }
    session_prefix "" {
      policy = "read"
    }
    agent_prefix "" {
      policy = "read"
    }
    query_prefix "" {
      policy = "read"
    }
    operator = "read"
    namespace_prefix "" {
      acl = "read"
      intention = "read"
      service_prefix "" {
        policy = "read"
      }
      node_prefix "" {
        policy = "read"
      }
    }' |  consul acl policy create -name anonymous -rules -
    consul acl token update -id anonymous -policy-name anonymous

mkdir -p /root/aws/policies
cat << EOF > /root/aws/policies/svc-policy.hcl
service_prefix "" {
  policy = "write"
}
EOF

consul acl policy create -name "svc-policy" -description "vault" -rules @/root/aws/policies/svc-policy.hcl
vault kv patch secret/consul svc_token=$(consul acl token create -description 'generic service' -policy-name 'svc-policy' -format=json | jq -r .SecretID)
vault kv get -field="svc_token" secret/consul

exit 0