#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

GITDIR="/root/gcp-gke"

cd ${GITDIR}/us-west-primary

# GKE Cluster should be built already during initial setup.
#terraform init
#terraform apply -auto-approve
./setkubectl.sh

# Setup Primary
ext_ip=$(kubectl get svc vault-primary-active-lb -o json | jq -r '.status.loadBalancer.ingress[].ip')
echo "Ext IP: ${ext_ip}"

kubectl exec -ti vault-primary-0 -- vault write -f sys/replication/dr/primary/enable primary_cluster_addr=https://${ext_ip}:8201

kubectl exec -ti vault-primary-0 -- vault write sys/replication/dr/primary/secondary-token id=dr -format=json | tee ${GITDIR}/tmp/secondary-token.json

# Setup Secondary
sleep 30
cd ../us-central-dr
    ./setkubectl.sh

token=$(jq -r '.wrap_info.token' < ${GITDIR}/us-west-primary/tmp/secondary-token.json)
kubectl exec -ti vault-dr-0 -- vault write sys/replication/dr/secondary/enable primary_api_addr=http://${ext_ip}:8200 token=${token}

sleep 30
echo "Secondary DR Cluster Status:"
kubectl exec -ti vault-dr-0 -- vault read sys/replication/dr/status
echo "Primary DR Cluster Status:"
kubectl --context=primary exec -it vault-primary-0 -- vault read sys/replication/dr/status

exit 0
