#!/bin/bash -l
# set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
GITDIR="/root/gcp-gke"

# Using zone for the region in tf makes smaller GKS footprint
gke_namespace=$(terraform output -state=${GITDIR}/us-west-primary/terraform.tfstate gke_namespace)

cd ${GITDIR}/us-west-primary
./setkubectl.sh

export VAULT_SKIP_VERIFY=true
export VAULT_ADDR="http://$(kubectl get svc vault-primary-ui -o json | jq -r '.status.loadBalancer.ingress[].ip'):8200"
grep "VAULT_ADDR=" /root/.bashrc || echo "export VAULT_ADDR=\"${VAULT_ADDR}\"" >> /root/.bashrc

export VAULT_TOKEN="$(jq -r '.root_token' < tmp/cluster-keys.json)"
grep "VAULT_TOKEN=" /root/.bashrc || echo "export VAULT_TOKEN=\"${VAULT_TOKEN}\"" >> /root/.bashrc

export TF_VAR_VAULT_ADDR=${VAULT_ADDR}
#grep "TF_VAR_VAULT_ADDR=" /root/.bashrc || echo "export TF_VAR_VAULT_ADDR="${VAULT_ADDR}" >> /root/.bashrc
export TF_VAR_VAULT_TOKEN=${VAULT_TOKEN}

# Set workdir
set-workdir ${GITDIR}/vault-administration

# Create Vault Policy with Terraform IaC
cd ${GITDIR}/vault-administration
terraform init
terraform apply -auto-approve

exit 0

