#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

cd us-west-primary
terraform init
terraform apply -auto-approve
./setkubectl.sh

helm repo add hashicorp https://helm.releases.hashicorp.com
helm install vault-primary hashicorp/vault -f vault.yaml


../scripts/init_vault.sh

exit 0
