#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

GITDIR="/root/gcp-gke"

cd ${GITDIR}/us-west-primary

terraform init
terraform apply -auto-approve
./setkubectl.sh

helm repo add hashicorp https://helm.releases.hashicorp.com
helm install vault-primary hashicorp/vault -f vault.yaml -f vault-hc-helm.yaml

kubectl apply -f vault-primary-active-lb.yaml
kubectl get svc vault-primary-active-lb

sleep 40
../scripts/init_vault.sh

exit 0
