version: "2"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
  - 8200
  - 8500
  - 8080
virtualmachines:
- name: vm
  image: debian-9
  shell: /bin/bash
  environment:
    ANOTHER: one
    ENV_VAR: value
  machine_type: g1-small
aws_accounts:
- name: consul
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
  - arn:aws:iam::aws:policy/PowerUserAccess
