#!/bin/bash -l

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

vpc=$(aws ec2 describe-vpcs | jq '[.. |."State"? | select(. == "available")] | length')
ami=$(aws ec2 describe-images --owners self --query 'Images[*].[ImageId]' --output text)

if [ $vpc -le 0 ]; then
  fail-message "VPCs did not provision successful."
  exit 1
elif [[ ! $(echo ${ami} | grep "ami") ]]; then
  fail-message "AMI did not provision successful."
  exit 1
else
  exit 0
fi
