#!/bin/bash -l
set -e

# wait for AWS Credentials
sleep 10

#install terraform
cd /tmp
echo "installing terraform..."
curl -O https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
unzip terraform_0.13.5_linux_amd64.zip
mv terraform /usr/local/bin/terraform
rm -f terraform_0.13.5_linux_amd64.zip

# env
export AWS_REGION=us-west-2

# path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc
echo "export AWS_REGION=${AWS_REGION}" >> ~/.bashrc


echo "Installing AWS CLI"
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
rm -rf aws awscliv2.zip

# aws cli
aws configure set default.region ${AWS_REGION}
aws ec2 create-default-vpc

#ssh
aws ec2 import-key-pair --key-name "instruqt" --public-key-material fileb://~/.ssh/id_rsa.pub
eval `ssh-agent -s`

cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF

#install vault
#cd /tmp
#echo "installing vault..."
#curl -O https://releases.hashicorp.com/vault/1.6.3/vault_1.6.3_linux_amd64.zip
#unzip *.zip
#mv vault /usr/local/bin/vault
#rm -f *.zip

mkdir -p /root/aws
set-workdir /root/aws
cd /root/aws
echo "cloning assets..."
git clone https://github.com/ppresto/instruqt-tracks.git
cp -r instruqt-tracks/consul-aws-ecs/assets/consul .
cp -r instruqt-tracks/consul-aws-ecs/assets/packer .
cp -r instruqt-tracks/consul-aws-ecs/assets/vpc .
cp -r instruqt-tracks/consul-aws-ecs/assets/ecs .
cp -r instruqt-tracks/consul-aws-ecs/assets/consul-ecs-agent .
rm -rf instruqt-tracks

# create image
cd /root/aws/packer/consul
./run-linux.sh > packer.out &


#provision vpc
cd /root/aws/vpc
echo "Provision VPC ..."
/usr/local/bin/terraform init
/usr/local/bin/terraform apply -auto-approve

# Start up Visual Studio Code server
# Create VSC startup script
cat <<-EOF > /etc/systemd/system/code-server.service
[Unit]
Description=Code Server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/usr/bin/code-server --host 0.0.0.0 --port 8443 --cert --auth none /root/aws/consul

[Install]
WantedBy=multi-user.target
EOF

# Add AWS keys to systemd environment
systemctl import-environment AWS_ACCESS_KEY_ID
systemctl import-environment AWS_SECRET_ACCESS_KEY

# Start VSC
systemctl enable code-server
systemctl start code-server

# Wait for AMI to be available
#until aws ec2 describe-images --owners self --query 'Images[*].[ImageId]' --output text; do
until aws ec2 describe-images --region ${AWS_REGION} --filters "Name=tag:Owner,Values=ppresto@hashicorp.com" --output text | grep is-immutable-consul; do
    echo "Waiting for AWS AMI to be available"
    sleep 1
done

#aws ec2 describe-images --owners self
#aws ec2 describe-images --region ${AWS_REGION} --filters "Name=tag:Owner,Values=ppresto@hashicorp.com" --output text

exit 0
