#!/bin/bash

# env
export AWS_REGION=us-west-2

# path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc
echo "export AWS_REGION=${AWS_REGION}" >> ~/.bashrc

set-workdir /root

# wait for AWS Credentials
sleep 10

# aws cli
aws configure set default.region ${AWS_REGION}
aws ec2 create-default-vpc

#ssh
aws ec2 import-key-pair --key-name "instruqt" --public-key-material file://~/.ssh/id_rsa.pub
eval `ssh-agent -s`

cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF

#install terraform
cd /tmp
echo "installing terraform..."
curl -O https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
unzip *.zip
mv terraform /usr/local/bin/terraform
rm -f *.zip
cd /root

#install consul
cd /tmp
echo "installing consul..."
curl -O https://releases.hashicorp.com/consul/1.8.0+ent/consul_1.8.0+ent_linux_amd64.zip
unzip *.zip
mv consul /usr/local/bin/consul
rm -f *.zip
cd /root

#install vault
cd /tmp
echo "installing vault..."
curl -O https://releases.hashicorp.com/vault/1.6.3/vault_1.6.3_linux_amd64.zip
unzip *.zip
mv vault /usr/local/bin/vault
rm -f *.zip

cd /root
echo "cloning assets..."
git clone https://github.com/ppresto/instruqt-tracks.git
cp -r instruqt-tracks/consul-aws-ecs/assets/consul .
cp -r instruqt-tracks/consul-aws-ecs/assets/packer .
cp -r instruqt-tracks/consul-aws-ecs/assets/vpc .
cp -r instruqt-tracks/consul-aws-ecs/assets/ecs .
cp -r instruqt-tracks/consul-aws-ecs/assets/consul-ecs-agent .
rm -rf instruqt-tracks

# create image
cd /root/packer/consul
./run-linux.sh > packer.out &

#provision vpc
cd /root/vpc
echo "Provision VPC ..."
/usr/local/bin/terraform init
/usr/local/bin/terraform apply -auto-approve

# Wait for AMI to be available
until aws ec2 describe-images --owners self --query 'Images[*].[ImageId]' --output text; do
    echo "Waiting for AWS AMI to be available"
    sleep 1
done

aws ec2 describe-images --owners self

exit 0
