#!/bin/bash -l


sleep 10
cd /root/aws/consul
echo "Provision Consul ..." >> output.txt
env >> output.txt
terraform init
terraform apply -auto-approve >> output.txt

if [[ $(terraform output dns_name| grep "amazonaws.com") ]]; then
    until curl -s -m 5 $(terraform output dns_name); do
        echo "Waiting for consul URL to be available..."
        sleep 5
    done
fi

vault kv get -field="svc_token" secret/consul

exit 0
