#!/bin/bash -l

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/aws/ecs
if [[ $(terraform output alb_hc_frontend| grep "amazonaws.com") ]]; then
    exit 0
else
    exit 1
fi
