#!/bin/bash -l

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

cd /root/aws/ecs
if [[ $(terraform output alb_hc_frontend) ]]; then
    until curl -s $(terraform output alb_hc_frontend); do
        echo "Waiting for frontend service to be available..."
        sleep 2
    done
    exit 0
else
    exit 1
fi
