#!/bin/bash -l

sleep 10
#path
#echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc

set-workdir /root/aws/ecs

sed -i "s/\/root\/aws.*/\/root\/aws\/ecs/" /etc/systemd/system/code-server.service
systemctl daemon-reload
systemctl restart code-server

exit 0
