#!/bin/bash -l
# set -e

GITDIR="/root/gcp-gke"

# Set workdir
set-workdir ${GITDIR}/us-west
cd ${GITDIR}/us-west
./setkubectl.sh

../scripts/uninstall_vault.sh vault-usw

# Create new KMS Key for New Primary.  Update terraform variables file with new name.
sed -i "s/\(key_ring\s\+= \).*/\1\"vault-unseal-ring-new\"/" terraform.tfvars
sed -i "s/\(crypto_key\s\+= \).*/\1\"vault-unseal-key-new\"/" terraform.tfvars

exit 0
