#!/bin/bash

#path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc

set-workdir /root/consul-ecs-agent

apt-get update -y
apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add –
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
apt-get update -y
apt-get install docker-ce docker-ce-cli containerd.io -y

exit 0
