#!/bin/bash

set-workdir /root/aws/consul-ecs-agent

sed -i "s/\/root\/aws.*/\/root\/aws\/consul-ecs-agent/" /etc/systemd/system/code-server.service
systemctl daemon-reload
systemctl restart code-server


exit 0
