#!/bin/bash
set -e

# Create /tmp/skip-check to disable this check
if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

[[ -f /bin/set-workdir ]] || fail-message "Uh oh, you're missing the set-workdir script. Please restart your track."

if [[ $(helm list -o json | jq -r '.[].name' | grep vault) ]]; then
    exit 0
else
    fail-message "Helm list shows: $(helm list -o json | jq -r '.[].name')"
fi

