#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

GITDIR="/root/gcp-gke"

#Build the GKE DR cluster in parallel to save time.
cd ${GITDIR}/us-central
terraform init
terraform apply -auto-approve &

cd ${GITDIR}/us-west

terraform init
terraform apply -auto-approve
./setkubectl.sh

helm repo add hashicorp https://helm.releases.hashicorp.com
helm install vault-usw hashicorp/vault -f vault.yaml -f vault-hc-helm.yaml

kubectl apply -f vault-usw-active-lb.yaml
kubectl get svc vault-usw-active-lb

sleep 40
../scripts/init_vault.sh

cd ${GITDIR}/vault-administration

# Set K8s and Vault Environment variables required by terraform.
source setenv.sh

terraform init
terraform apply -auto-approve

exit 0
