#!/bin/bash -l

# Enable bash history
HISTFILE=/root/.bash_history
set -o history

gke_namespace=default

GITDIR="/root/gcp-gke"
cd ${GITDIR}/us-central
./setkubectl.sh

# Authenticate to Vault
kubectl --context=usc \
exec -ti vault-usc-0 -- vault login \
$(jq -r '.root_token' < tmp/vault-usc-cluster-keys.json)

# Get vault-active pod
vault_primary_active=$(kubectl --context=usw  --namespace ${gke_namespace} get pod --selector="vault-active=true" --output=jsonpath={.items..metadata.name})

# Create DR Operator Batch Token using the new "vault-dr-token" policy
kubectl --context=usw --namespace ${gke_namespace} exec -it ${vault_primary_active} -- vault token create -format=json -orphan -type=batch -policy=vault-dr-token | jq -r '.auth.client_token' | tee ${GITDIR}/us-west/tmp/dr-batch-token
dr_batch_token=$(cat ${GITDIR}/us-west/tmp/dr-batch-token)

# Cause disaster by completely removing vault and its data stores so there is nothing left.
# Include GKE --context
cd ${GITDIR}/us-west
./setkubectl.sh
../scripts/uninstall_vault.sh vault-usw

# Promote Vault DR to Primary
vault_dr_active=$(kubectl --context=usc  --namespace ${gke_namespace} get pod --selector="vault-active=true" --output=jsonpath={.items..metadata.name})

kubectl --context=usc exec -it ${vault_dr_active} -- vault write sys/replication/dr/secondary/promote dr_operation_token=${dr_batch_token}

sleep 1
kubectl --context=usc delete pods -l vault-active=false

exit 0
