#!/bin/bash -l
# set -e

# Allow instruqt time to do its thing
sleep 10

# install command line tools
snap install kubectl --classic
snap install helm --classic

# clone the terraform-guides repo
git clone https://github.com/ppresto/gcp-gke.git
GITDIR="/root/gcp-gke"

# Set workdir
set-workdir ${GITDIR}


# Store our project ID as a Terraform env var
grep $INSTRUQT_GCP_PROJECT_GCP_PROJECT_PROJECT_ID /root/.bashrc || echo "export TF_VAR_gcp_project=\"$INSTRUQT_GCP_PROJECT_GCP_PROJECT_PROJECT_ID\"" >> /root/.bashrc
echo "export GOOGLE_PROJECT=\"$INSTRUQT_GCP_PROJECT_GCP_PROJECT_PROJECT_ID\"" >> /root/.bashrc

# Add GCP Credentials to our profile and env
export GOOGLE_CREDENTIALS=$(echo $INSTRUQT_GCP_PROJECT_GCP_PROJECT_SERVICE_ACCOUNT_KEY | base64 -d | jq 'tostring')
export TF_VAR_GOOGLE_CREDENTIALS="${GOOGLE_CREDENTIALS}"
echo "export GOOGLE_CREDENTIALS=$GOOGLE_CREDENTIALS" >> /root/.bashrc
#echo "export TF_VAR_GOOGLE_CREDENTIALS=$GOOGLE_CREDENTIALS" >> /root/.bashrc

# Create VSC startup script
cat <<-EOF > /etc/systemd/system/code-server.service
[Unit]
Description=Code Server
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/usr/bin/code-server --host 0.0.0.0 --port 8443 --cert --auth none ${GITDIR}

[Install]
WantedBy=multi-user.target
EOF

# Add GCP creds to systemd environment
systemctl import-environment INSTRUQT_GCP_PROJECT_GCP_PROJECT_PROJECT_ID
systemctl import-environment TF_VAR_project
systemctl import-environment GOOGLE_CREDENTIALS

# Start VSC
systemctl enable code-server
systemctl start code-server

exit 0
